version: '3'
services: 
  mongo: 
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "~/data:/data/db"
  api:
    build: .
    environment: 
      MONGO_URL: mongodb://mongo:27017/i-know
      PORT: 3001
    ports: 
      - "3001:3001"
    depends_on: 
      - mongo
    restart: always