name: Build API Server

on:
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build
        run: |
          yarn
          yarn build
      - name: Run test
        run: yarn test
        env:
          CI: true